on: push
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish to FTP
      run: ./publish_ftp.sh
      env:
        FTP_USER: ${{ secrets.POMAHAJME_FTP_USER }}
        FTP_PASS: ${{ secrets.POMAHAJME_FTP_PASS }}
        FTP_HOST: ${{ secrets.POMAHAJME_FTP_HOST }}